import { test, expect, type Page } from '@playwright/test'
async function login(page: Page, user: string) {
  await page.goto('/')
  await page.locator('#username').selectOption(user)
  await page.locator('#password').fill('browser-test-password-only')
  await page.getByRole('button', { name: 'Se connecter' }).click()
  await expect(page.locator('#status')).toContainText('Connecté')
}
test('Deux navigateurs : présence, GPS désordonnés, resynchronisation et SSE', async ({ browser }) => {
  const a = await browser.newContext(), b = await browser.newContext()
  const client = await a.newPage(), dispatcher = await b.newPage()
  const errors: string[] = []
  client.on('pageerror', e => errors.push(e.message)); dispatcher.on('pageerror', e => errors.push(e.message))
  await login(client, 'camille'); await login(dispatcher, 'dispatcher')
  await expect(client.locator('#presence')).toContainText('dispatcher')
  await dispatcher.locator('#pitfall').click()
  await expect(dispatcher.locator('#pitfall-results')).toContainText('stale')
  await expect(client.locator('#journal')).toContainText('révision 5')
  await expect(dispatcher.locator('#journal')).toContainText('révision 5')
  await a.setOffline(true)
  await expect(client.locator('#status')).toContainText('Hors ligne')
  await dispatcher.locator('#pitfall').click()
  await a.setOffline(false)
  await expect(client.locator('#status')).toContainText('Connecté')
  await expect(client.locator('#journal')).toContainText('Resynchronisation')
  await client.locator('#transport').selectOption('sse')
  await expect(client.locator('#status')).toContainText('SSE')
  await expect(client.locator('#journal')).toContainText('Snapshot SSE')
  await client.screenshot({ path: 'test-results/livraison-client.png', fullPage: true })
  await dispatcher.screenshot({ path: 'test-results/livraison-dispatcher.png', fullPage: true })
  expect(errors).toEqual([])
  await a.close(); await b.close()
})
test('WebRTC : client et livreur échangent via RTCDataChannel', async ({ browser }) => {
  const a = await browser.newContext(), b = await browser.newContext()
  const client = await a.newPage(), driver = await b.newPage()
  await login(client, 'camille'); await login(driver, 'sam')
  await driver.locator('#p2p').click()
  await expect(client.locator('#p2p-status')).toContainText('Canal livraison établi', { timeout: 15000 })
  await expect(driver.locator('#p2p-status')).toContainText('Canal livraison établi', { timeout: 15000 })
  await driver.locator('#send-position').click()
  await expect(client.locator('#p2p-status')).toContainText('GPS')
  await expect(driver.locator('#journal')).toContainText('ICE')
  await a.close(); await b.close()
})

