import test from 'node:test'
import assert from 'node:assert/strict'
import { socketEvent, running, login, client, delay } from './helpers.ts'
test('Deux clients convergent, la room voisine reste isolée, reconnexion par snapshot', async t => {
  const server = await running()
  t.after(() => server.app.close())
  const aCookie = await login(server, 'camille')
  const a = await client(server.url, aCookie), b = await client(server.url, aCookie)
  const other = await client(server.url, await login(server, 'jules'))
  t.after(() => { a.close(); b.close(); other.close() })
  await a.timeout(2000).emitWithAck('join', 'commande:cmd-101')
  await b.timeout(2000).emitWithAck('join', 'commande:cmd-101')
  await other.timeout(2000).emitWithAck('join', 'commande:cmd-102')
  let leaked = false; other.on('state', () => { leaked = true })
  const first = socketEvent(a, 'state'), second = socketEvent(b, 'state')
  const base = Date.now()
  assert.equal(await server.state.apply('liv-1', { lat: 43.53, lon: 5.45, at: base }), 'accepted')
  const [one, two] = await Promise.all([first, second])
  assert.deepEqual(one, two)
  assert.equal(await server.state.apply('liv-1', { lat: 43.57, lon: 5.45, at: base - 1000 }), 'stale')
  b.disconnect()
  await server.state.apply('liv-1', { lat: 43.531, lon: 5.45, at: base + 2000 })
  await delay(30)
  assert.equal(leaked, false)
  b.connect(); await socketEvent(b, 'connect')
  const result = await b.timeout(2000).emitWithAck('join', 'commande:cmd-101')
  assert.equal(result.snapshot.livreurs[0].position.at, base + 2000)
})
test('Présence : plusieurs onglets, grâce, départ explicite et purge', async t => {
  const server = await running()
  t.after(() => server.app.close())
  const cookie = await login(server, 'camille')
  const a = await client(server.url, cookie), b = await client(server.url, cookie)
  t.after(() => { a.close(); b.close() })
  await a.timeout(2000).emitWithAck('join', 'commande:cmd-101')
  const joined = await b.timeout(2000).emitWithAck('join', 'commande:cmd-101')
  assert.deepEqual(joined.users, ['camille'])
  b.disconnect()
  const during = await a.timeout(2000).emitWithAck('join', 'commande:cmd-101')
  assert.deepEqual(during.users, ['camille'])
  await delay(300)
  assert.deepEqual((await a.timeout(2000).emitWithAck('join', 'commande:cmd-101')).users, ['camille'])
})
test('SSE HTTP : refus IDOR, snapshot initial, curseur périmé et rejeu', async t => {
  const server = await running()
  t.after(() => server.app.close())
  const cookie = await login(server, 'camille')
  assert.equal((await server.app.inject({ url: '/api/stream?room=commande:cmd-102', headers: { cookie } })).statusCode, 403)
  const read = async (cursor?: string) => {
    const controller = new AbortController()
    const response = await fetch(server.url + '/api/stream?room=commande:cmd-101', { headers: { cookie, ...(cursor ? { 'Last-Event-ID': cursor } : {}) }, signal: controller.signal })
    const part = await response.body!.getReader().read()
    controller.abort()
    return Buffer.from(part.value!).toString()
  }
  const initial = await read()
  assert.match(initial, /event: resync-needed/)
  const cursor = initial.match(/id: (.+)/)![1]
  await server.state.apply('liv-1', { lat: 43.53, lon: 5.45, at: Date.now() })
  assert.match(await read(cursor), /event: state/)
  assert.match(await read('unknown:0'), /event: resync-needed/)
})

